apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongodb-pvc
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  resources:
    requests:
      storage: 5Gi
  accessModes:
    - ReadWriteOnce
